### ISSUE TITLE
ITMS-90683: Missing Purpose String in Info.plist

### ISSUE THREAD

**Issue by huguesfcadets** [cadets-ca/ets#54]
- Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSBluetoothAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy). 
After you’ve corrected the issues, you can upload a new binary to App Store Connect. 
Best regards,
The App Store Team

**Comment by kirvanp** [comment]
The app has support for bluetooth beacons, however it is off by default and I haven't maintained it in a couple years so there may be bugs. Basically, a bluetooth beacon is about the size of a deck of cards and goes in the glider. The app then knows the distance to the glider and based on that it can automatically record a glider as landed when it gets close to the timekeeper. It can also warn the user about error states, such as if a glider is marked flying but is actually on the ground. It's pretty neat. 

You can try it out if you wish by using iPhones as fake bluetooth beacons. To do so, go Settings > Timesheets on your iPad and turn on iBeacon Assistance. Then, on your phone, go to the same place but instead turn on Use Devices as Beacon and give it a number (doesn't matter which one). Then, on the iPad, add an airplane, perhaps a towplane for demo purposes. Select the towplane, and give it the same beacon number as your phone. Then mark it as having taken off. If you walk away and walk back, when you walk back it will record your towplane as being landed. It even works when the iPad screen is off, which means it can record landings without using much battery. In one version, it would speak "Glider 1 Landed" or something like that, but I don't know if I still have that in. 

Overall, the goal was to reduce errors. No matter how intuitive the app is, users are going to bungle it up by marking the wrong planes as landed or taken off, especially when there are 8+ planes being used at once. So besides being fun, this did have real potential to improve the app. That said, it was a side project that I played with at some flying sites, we weren't using it at summer camp.
