### ISSUE TITLE
No back button on iPhone

### ISSUE THREAD

**Issue by huguesfcadets** [cadets-ca/ets#55]
To resolve this issue, please run your app on a device to identify any issues, then revise and resubmit your app for review.

If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue. For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue.

Resources

For information about testing your app and preparing it for review, please see [Technical Note TN2431: App Testing Guide. ](https://developer.apple.com/library/archive/technotes/tn2431/_index.html)

For a networking overview, please review [About Networking](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/Introduction/Introduction.html).

**Comment by huguesfcadets** [comment]
(on behalf of @kirvanp )
As far as the back buttons being gone on the iPhone version, I have noticed this since iOS 13 came out. I suggest updating the target to iOS 13.4, as the iPads are capable of running that, and doing the recommended adjustments to the code. Upgrading the target will make Xcode more willing to give warnings for code that was meant for iOS 10-12 that might no longer work. It will also result in a smaller app size as iOS 13 has the Swift runtime built into the OS rather than included with the app.

**Comment by huguesfcadets** [comment]
# Setting target to iOS13
When changing target to iOS 13; 47 warning of deprecated things from iOS 12 and 13 are found. Nothing about **traitCollectionDidChange** (see below).
Changing the target to iOS 13 will be a new project with specific issues to resolve deprecated usage.

# Findings about the issue.
Found that **traitCollectionDidChange** not called at the same moment when on iOS 10 vs when on iOS 13. 
For example, when the **addAircraftPopover** is shown under iOS 13, **traitCollectionDidChange** is not called. But if you change the orientation of the device, it is called and the "Done" button appears.
The function **addOrRemoveDonButtonGivenTraitCollection** is called from 8 other places.

# Proposed changes
Proposed changes, for contexts similar to the one in **AddAircraftPopover**, is to remove the need of **addOrRemoveDoneButtonGivenTraitCollection** by adding the button for the specific trait.

**Comment by kirvanp** [comment]
Fix looks good. I would point out that if you do not change the target, you will have to test these modifications against iOS 10, 11, and 12 in case they cause regressions on those systems. If you do not raise the target, it is fair game for one of Apple’s reviewers to run it on those systems. Raising the target to iOS 13 does not cause any new problems, we are using deprecated APIs whether the warnings show up or not. It simply makes us more aware of the problems that have been there since iOS 13 came out and excuses us from having to test against older OSes. 

PK
